name: Typst Library Release

# Define permissions at the workflow level
permissions:
  contents: write
  packages: write

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  # Add manual trigger for existing versions
  workflow_dispatch:
    inputs:
      version:
        description: 'Specific version to release (leave empty for auto-detection)'
        required: false
        default: ''

jobs:
  detect-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for checking changes

      - name: Set up Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Detect version
        id: detect-version
        run: |
          # Check if a manual version was specified
          if [[ "${{ github.event.inputs.version }}" != "" ]]; then
            MANUAL_VERSION="${{ github.event.inputs.version }}"
            
            # List all directories to find the namespace and version
            echo "Searching for version directory..."
            
            # Use the current directory (repository root) for path resolution
            NAMESPACE_PATHS=$(find . -type d -name "${MANUAL_VERSION}" | grep -v "node_modules" | grep -v ".git" || echo "")
            
            if [[ -n "$NAMESPACE_PATHS" ]]; then
              # Get the first matching namespace path
              VERSION_PATH=$(echo "$NAMESPACE_PATHS" | head -n 1)
              NAMESPACE=$(echo "$VERSION_PATH" | cut -d'/' -f2)
              
              echo "Found version at path: ${VERSION_PATH}"
              echo "Namespace: ${NAMESPACE}"
              echo "Version: ${MANUAL_VERSION}"
              
              # Use GITHUB_OUTPUT environment file instead of set-output command
              echo "version=${MANUAL_VERSION}" >> $GITHUB_OUTPUT
              echo "namespace=${NAMESPACE}" >> $GITHUB_OUTPUT
              echo "version_path=${VERSION_PATH}" >> $GITHUB_OUTPUT
              echo "skip_validation=true" >> $GITHUB_OUTPUT
              exit 0
            else
              echo "Error: Manually specified version ${MANUAL_VERSION} not found in repository structure"
              echo "Directory listing for debugging:"
              find . -type d -maxdepth 3
              exit 1
            fi
          fi
          
          # Get the latest commit hash
          LATEST_COMMIT=$(git rev-parse HEAD)
          
          # Get the list of changed files in the latest commit or PR
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            # For PRs, compare with base branch
            CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} $LATEST_COMMIT)
          else
            # For direct pushes, use the parent commit
            CHANGED_FILES=$(git diff --name-only $LATEST_COMMIT^1 $LATEST_COMMIT 2>/dev/null || echo "")
          fi
          
          # Extract the new version folder
          NEW_VERSION=""
          NAMESPACE_PATH=""
          VERSION_PATH=""
          
          for FILE in $CHANGED_FILES; do
            # Match patterns like /<namespace>/<version>/... with relative paths
            if [[ $FILE =~ ^([^/]+)/([^/]+)/ ]]; then
              NAMESPACE="${BASH_REMATCH[1]}"
              VERSION="${BASH_REMATCH[2]}"
              if [[ "$NEW_VERSION" == "" ]]; then
                NEW_VERSION=$VERSION
                NAMESPACE_PATH=$NAMESPACE
                VERSION_PATH="${NAMESPACE}/${VERSION}"
              elif [[ "$NEW_VERSION" != "$VERSION" ]]; then
                echo "Error: Multiple version folders modified in one commit"
                exit 1
              fi
            fi
          done
          
          # If no changes were detected and this is a manual run, find the latest version
          if [[ "$NEW_VERSION" == "" && "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            # Find all version directories
            VERSION_DIRS=$(find . -mindepth 2 -maxdepth 2 -type d | grep -v "node_modules" | grep -v ".git" | sort -V)
            if [[ -n "$VERSION_DIRS" ]]; then
              # Get the latest version directory
              LATEST_VERSION_DIR=$(echo "$VERSION_DIRS" | tail -n 1)
              NEW_VERSION=$(basename "$LATEST_VERSION_DIR")
              NAMESPACE_PATH=$(dirname "$LATEST_VERSION_DIR" | sed 's|^./||' | xargs basename)
              VERSION_PATH="${NAMESPACE_PATH}/${NEW_VERSION}"
              echo "No changes detected, using latest version directory: ${NEW_VERSION}"
              echo "skip_validation=true" >> $GITHUB_OUTPUT
            else
              echo "No version directories found"
              echo "Directory listing for debugging:"
              find . -type d -maxdepth 3
              exit 1
            fi
          elif [[ "$NEW_VERSION" == "" ]]; then
            echo "No version folder changes detected"
            exit 1
          fi
          
          # Skip validation if requested or if this is a manual run
          if [[ "${{ github.event_name }}" != "workflow_dispatch" ]]; then
            # Check if changes only affect the new version folder
            for FILE in $CHANGED_FILES; do
              if [[ ! $FILE =~ ^${NAMESPACE_PATH}/${NEW_VERSION}/ ]]; then
                echo "Warning: Changes include files outside the new version folder"
                echo "validation_warning=true" >> $GITHUB_OUTPUT
              fi
            done
          fi
          
          echo "version=${NEW_VERSION}" >> $GITHUB_OUTPUT
          echo "namespace=${NAMESPACE_PATH}" >> $GITHUB_OUTPUT
          echo "version_path=${VERSION_PATH}" >> $GITHUB_OUTPUT
          echo "Version detected: ${NEW_VERSION} in namespace ${NAMESPACE_PATH}"

      - name: Check if release exists
        if: steps.detect-version.outputs.version != ''
        id: check-release
        run: |
          # Check if the release already exists
          RELEASE_EXISTS=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/releases/tags/v${{ steps.detect-version.outputs.version }}")
            
          if [[ "$RELEASE_EXISTS" == "200" ]]; then
            echo "Release already exists for version ${{ steps.detect-version.outputs.version }}"
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "No existing release found for version ${{ steps.detect-version.outputs.version }}"
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create release archives
        if: steps.detect-version.outputs.version != '' && steps.check-release.outputs.exists != 'true'
        id: create-archives
        run: |
          VERSION="${{ steps.detect-version.outputs.version }}"
          NAMESPACE="${{ steps.detect-version.outputs.namespace }}"
          VERSION_PATH="${{ steps.detect-version.outputs.version_path }}"
          
          # Debug info
          echo "Creating archives for ${VERSION_PATH}"
          ls -la "${VERSION_PATH}" || echo "Directory not found"
          
          # Create archives directory
          mkdir -p ./archives
          
          # Check if directory exists
          if [[ ! -d "${VERSION_PATH}" ]]; then
            echo "Error: Version directory not found: ${VERSION_PATH}"
            # Try alternative paths
            echo "Searching for version directory..."
            find . -name "${VERSION}" -type d
            exit 1
          fi
          
          # Create tar.gz archive
          tar -czf "./archives/${NAMESPACE}-${VERSION}.tar.gz" "${VERSION_PATH}"
          
          # Create zip archive
          zip -r "./archives/${NAMESPACE}-${VERSION}.zip" "${VERSION_PATH}"
          
          echo "targz=./archives/${NAMESPACE}-${VERSION}.tar.gz" >> $GITHUB_OUTPUT
          echo "zip=./archives/${NAMESPACE}-${VERSION}.zip" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        if: steps.detect-version.outputs.version != '' && steps.check-release.outputs.exists != 'true' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
        id: create-release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.detect-version.outputs.version }}
          name: Version ${{ steps.detect-version.outputs.version }}
          draft: false
          prerelease: false
          body: |
            Release of version ${{ steps.detect-version.outputs.version }}
            ${{ steps.detect-version.outputs.validation_warning == 'true' && '⚠️ Warning: This release may include changes outside the version directory.' || '' }}
          files: |
            ${{ steps.create-archives.outputs.targz }}
            ${{ steps.create-archives.outputs.zip }}
